package dk.grinhouse.api.controllers;


import dk.grinhouse.api.OpenApiConfig;
import dk.grinhouse.api.services.ProfileService;
import dk.grinhouse.models.ThresholdProfile;

import io.swagger.v3.oas.annotations.Operation;

import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@Tag(name = OpenApiConfig.TAG_PROFILE_CONTROLLER)
public class ProfileController
{
  private final ProfileService profileService;

  public ProfileController(ProfileService profileService)
  {
    this.profileService = profileService;
  }

  @Operation(summary = "returns a list of all profiles", description = "")
  @GetMapping("/api/profile")
  public ResponseEntity<List<ThresholdProfile>> getAllProfiles()
  {
    return ResponseEntity.ok(profileService.getAllProfiles());
  }

  @Operation(summary = "returns the current active profile", description = "")
  @GetMapping("/api/profile/current")
  public ResponseEntity<ThresholdProfile> getCurrentProfile()
  {
    return ResponseEntity.ok(profileService.getCurrentProfile());
  }

  @Operation(summary = "create new profile", description = "id can be any value such as 0 since it will be replaced by autogenerated id on insert to the database")
  @PostMapping("/api/profile")
  public ResponseEntity insertNewProfile(@RequestBody ThresholdProfile newProfile)
  {
      profileService.InsertNewProfile(newProfile);
      return ResponseEntity.ok(HttpStatus.CREATED);
  }

  @Operation(summary = "edit profile", description = "")
  @PutMapping("/api/profile")
  public ResponseEntity updateProfile(@RequestBody ThresholdProfile newProfile)
  {
    profileService.UpdateProfile(newProfile);
    return ResponseEntity.ok(HttpStatus.OK);
  }

  @Operation(summary = "delete profile by id", description = "")
  @DeleteMapping("/api/profile/{id}")
  public ResponseEntity deleteProfile(@PathVariable("id") int id)
  {
    profileService.DeleteProfile(id);
    return ResponseEntity.ok(HttpStatus.OK);
  }
}
